run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - gofmt
    - goimports
    - revive

issues:
  exclude-use-default: false

